[workspace]
authors = ["Liam Pohlmann <liam.pohlmann@gmail.com>"]
channels = ["conda-forge"]
name = "hummingbird"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
cmake = ">=4.4.2,<5"
ninja = ">=1.13.2,<2"
armadillo = ">=15.4.2,<16"
hdf5 = ">=2.1.0,<3"
doxygen = ">=1.17.0,<2"
graphviz = ">=14.1.2,<15"
gtest = ">=1.17.0,<2"
nlohmann_json = ">=3.12.0,<4"
