// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026, Liam Pohlmann

#ifndef HUMMINGBIRD_PHYSICS_PARSED_VOLUMETRIC_SOURCE_H_
#define HUMMINGBIRD_PHYSICS_PARSED_VOLUMETRIC_SOURCE_H_

namespace hummingbird {

}

#endif // HUMMINGBIRD_PHYSICS_PARSED_VOLUMETRIC_SOURCE_H_
